/**
 * Global lookup type IDs - These are the same across the entire application
 * These IDs come from lookup_type model in the backend
 */
export const LOOKUP_TYPE_IDS = {
  INVESTOR_TITLE: 2,
  NATIONALITY: 3,
  CITIZENSHIP: 4,
  INVESTOR_TYPE: 5,
  SOURCE_OF_INVESTMENT: 6,
  OWNERSHIP_TYPE: 7,
  COUNTRY: 8,
  EDUCATION_BACKGROUND: 9,
  PROJECT_STATUS: 10,
  DECISION_TYPE: 11,
  DECISION_BODY: 12,
  LICENCING_ORGAN: 13,
  LAND_SOURCE: 14,
  INDUSTRY_SCALE: 15,
  UNIT_OF_MEASUREMENT: 16,
  BUDGET_YEAR: 17,
  MONTH: 18,
  BANK_NAME_FINANCIAL_INSTITUTIONS: 19,
  REQUEST_STATUS: 20,
  REASON_OF_TERMINATION: 21,
  GENDER: 22,
  ETHNIC_GROUP: 23,
  PROJECT_SITE: 24,
  DOCUMENT_TYPE: 27,
  MONITORING_CHECKLIST: 28,
  DEMAND_TYPE: 29,
  LETTER_TEMPLATE_TYPE: 30,
  REQUEST_TYPE: 31,
  PERFORMANCE_DECLINE_REASONS: 32,
  APPROVING_BODY: 34,
  SOCIAL_RESPONSIBILITY_TYPE: 35,
  DUTY_FREE_COMMODITY: 36,
};

/**
 * Grouped lookup types for convenience
 * Useful to fetch multiple related lookups
 */
export const LOOKUP_GROUPS = {
  INVESTOR_FORM: [
    LOOKUP_TYPE_IDS.INVESTOR_TITLE,
    LOOKUP_TYPE_IDS.GENDER,
    LOOKUP_TYPE_IDS.ETHNIC_GROUP,
    LOOKUP_TYPE_IDS.NATIONALITY,
    LOOKUP_TYPE_IDS.CITIZENSHIP,
    LOOKUP_TYPE_IDS.INVESTOR_TYPE,
    LOOKUP_TYPE_IDS.SOURCE_OF_INVESTMENT,
    LOOKUP_TYPE_IDS.OWNERSHIP_TYPE,
    LOOKUP_TYPE_IDS.COUNTRY,
    LOOKUP_TYPE_IDS.EDUCATION_BACKGROUND,
  ],

  PROJECT_FORM: [
    LOOKUP_TYPE_IDS.PROJECT_STATUS,
    LOOKUP_TYPE_IDS.PROJECT_SITE,
    LOOKUP_TYPE_IDS.LAND_SOURCE,
    LOOKUP_TYPE_IDS.DECISION_BODY,
    LOOKUP_TYPE_IDS.DECISION_TYPE,
    LOOKUP_TYPE_IDS.LICENCING_ORGAN,
    LOOKUP_TYPE_IDS.INDUSTRY_SCALE,
  ],

  PROJECT_DOC_FORM: [LOOKUP_TYPE_IDS.DOCUMENT_TYPE],
  PROJECT_STATUS_FIELDS: [LOOKUP_TYPE_IDS.PROJECT_STATUS],

  DEMAND_FORM: [
    LOOKUP_TYPE_IDS.REQUEST_STATUS,
    LOOKUP_TYPE_IDS.BUDGET_YEAR,
    LOOKUP_TYPE_IDS.DEMAND_TYPE,
  ],

  LOAN_FORM: [
    LOOKUP_TYPE_IDS.REQUEST_STATUS,
    LOOKUP_TYPE_IDS.BANK_NAME_FINANCIAL_INSTITUTIONS,
    LOOKUP_TYPE_IDS.BUDGET_YEAR,
  ],

  POWER_PROBLEM_FORM: [LOOKUP_TYPE_IDS.REQUEST_STATUS],

  CHECKLIST_FORM: [LOOKUP_TYPE_IDS.MONITORING_CHECKLIST],

  STATISTICAL_REPORT: [
    LOOKUP_TYPE_IDS.NATIONALITY,
    LOOKUP_TYPE_IDS.GENDER,
    LOOKUP_TYPE_IDS.PROJECT_STATUS,
    LOOKUP_TYPE_IDS.DECISION_BODY,
    LOOKUP_TYPE_IDS.REQUEST_STATUS,
    LOOKUP_TYPE_IDS.DEMAND_TYPE,
    LOOKUP_TYPE_IDS.BANK_NAME_FINANCIAL_INSTITUTIONS,
  ],

  REPORT: [
    LOOKUP_TYPE_IDS.DECISION_BODY,
    LOOKUP_TYPE_IDS.DECISION_TYPE,
    LOOKUP_TYPE_IDS.LAND_SOURCE,
    LOOKUP_TYPE_IDS.REQUEST_STATUS,
    LOOKUP_TYPE_IDS.PROJECT_STATUS,
    LOOKUP_TYPE_IDS.REQUEST_TYPE,
    LOOKUP_TYPE_IDS.DEMAND_TYPE,
    LOOKUP_TYPE_IDS.OWNERSHIP_TYPE,
  ],

  TERMINATION_FORM: [
    LOOKUP_TYPE_IDS.REQUEST_STATUS,
    LOOKUP_TYPE_IDS.APPROVING_BODY,
  ],

  EXTENSION_FORM: [
    LOOKUP_TYPE_IDS.REQUEST_STATUS,
    LOOKUP_TYPE_IDS.APPROVING_BODY,
  ],

  LETTER_TEMPLATE_FORM: [LOOKUP_TYPE_IDS.LETTER_TEMPLATE_TYPE],

  REQUEST_FORM: [LOOKUP_TYPE_IDS.REQUEST_TYPE, LOOKUP_TYPE_IDS.REQUEST_STATUS],

  SOCIAL_RESPONSIBILITY_FORM: [LOOKUP_TYPE_IDS.SOCIAL_RESPONSIBILITY_TYPE],

  DUTY_FREE_FORM: [
    LOOKUP_TYPE_IDS.DUTY_FREE_COMMODITY,
    LOOKUP_TYPE_IDS.UNIT_OF_MEASUREMENT,
  ],

  PRODUCTION_CAPACITY_FIELDS: [
    LOOKUP_TYPE_IDS.PERFORMANCE_DECLINE_REASONS,
    LOOKUP_TYPE_IDS.UNIT_OF_MEASUREMENT,
  ],

  PRODUCTION_FORM: [
    LOOKUP_TYPE_IDS.BUDGET_YEAR,
    LOOKUP_TYPE_IDS.MONTH,
    LOOKUP_TYPE_IDS.UNIT_OF_MEASUREMENT,
  ],
};
