export const PROJECT_STATUS_IDS = {
  PRE_IMPLEMENTED: 187,
  NOT_IMPLEMENTED: 188,
  UNDER_CONSTRUCTION: 189,
  UNDER_CONSTRUCTION_ABANDONED: 190,
  CONSTRUCTION_ABANDONED: 191,
  CONSTRUCTION_COMPLETE_ABANDONED: 192,
  CONSTRUCTION_COMPLETE: 193,
  OPERATIONAL: 194,
  OPERATIONAL_ABANDONED: 195,
  SUSPENDED: 327,
  TERMINATED: 352,
};

export const PROJECT_STATUS_TRANSITIONS = {
  [PROJECT_STATUS_IDS.NOT_IMPLEMENTED]: [
    PROJECT_STATUS_IDS.NOT_IMPLEMENTED,
    PROJECT_STATUS_IDS.PRE_IMPLEMENTED,
    PROJECT_STATUS_IDS.UNDER_CONSTRUCTION,
    PROJECT_STATUS_IDS.CONSTRUCTION_COMPLETE,
    PROJECT_STATUS_IDS.OPERATIONAL,
    PROJECT_STATUS_IDS.SUSPENDED,
  ],
  [PROJECT_STATUS_IDS.PRE_IMPLEMENTED]: [
    PROJECT_STATUS_IDS.PRE_IMPLEMENTED,
    PROJECT_STATUS_IDS.UNDER_CONSTRUCTION,
    PROJECT_STATUS_IDS.CONSTRUCTION_COMPLETE,
    PROJECT_STATUS_IDS.OPERATIONAL,
    PROJECT_STATUS_IDS.SUSPENDED,
  ],
  [PROJECT_STATUS_IDS.UNDER_CONSTRUCTION]: [
    PROJECT_STATUS_IDS.UNDER_CONSTRUCTION,
    PROJECT_STATUS_IDS.CONSTRUCTION_COMPLETE,
    PROJECT_STATUS_IDS.OPERATIONAL,
    PROJECT_STATUS_IDS.CONSTRUCTION_ABANDONED,
    PROJECT_STATUS_IDS.SUSPENDED,
  ],
  [PROJECT_STATUS_IDS.CONSTRUCTION_ABANDONED]: [
    PROJECT_STATUS_IDS.CONSTRUCTION_ABANDONED,
    PROJECT_STATUS_IDS.UNDER_CONSTRUCTION,
    PROJECT_STATUS_IDS.SUSPENDED,
  ],
  [PROJECT_STATUS_IDS.CONSTRUCTION_COMPLETE]: [
    PROJECT_STATUS_IDS.CONSTRUCTION_COMPLETE,
    PROJECT_STATUS_IDS.OPERATIONAL,
    PROJECT_STATUS_IDS.SUSPENDED,
  ],
  [PROJECT_STATUS_IDS.OPERATIONAL]: [
    PROJECT_STATUS_IDS.OPERATIONAL,
    PROJECT_STATUS_IDS.OPERATIONAL_ABANDONED,
    PROJECT_STATUS_IDS.SUSPENDED,
  ],
  [PROJECT_STATUS_IDS.OPERATIONAL_ABANDONED]: [
    PROJECT_STATUS_IDS.OPERATIONAL_ABANDONED,
    PROJECT_STATUS_IDS.OPERATIONAL,
    PROJECT_STATUS_IDS.SUSPENDED,
  ],
  [PROJECT_STATUS_IDS.SUSPENDED]: [PROJECT_STATUS_IDS.SUSPENDED],
};
